Add support for NCLOB column type
laurenz/oracle_fdw pull request #563
Opened 2022-12-23 11:29 UTC by intgr

This uses the `TO_CLOB()` Oracle function to convert NCLOB values into CLOB values.

Doc: https://docs.oracle.com/database/121/SQLRF/functions218.htm

Do you see any downsides to doing this?

Only tested with SELECT & VACUUM.

The comment in the NCLOB handling code previously stated:

 					 * We don't support NCLOB because Oracle cannot
					 * transform it to the client character set automatically.

I have not verified whether this trick solves the character set conversion issue.

2022-12-23 11:33 UTC, laurenz commented
Thanks for the initiative!
I think that this is missing write support. A regression test is also necessary, but I could help with that.

2022-12-30 14:07 UTC, intgr commented
Added tests. Inserting seems to work fine using the same logic as CLOB type.

Or are there any gotchas that didn't occur to me?

2022-12-30 14:14 UTC, intgr commented on expected/oracle_fdw.out
> +CONTEXT:  COPY typetest1, line 1, column u: "\x01020304"
Oops, I have messed up tests here, will fix in a moment.

2022-12-30 14:28 UTC, intgr commented on oracle_fdw.c
> +				format = "%s(TO_CLOB(%s%s))";
Seems like the parenthesis around `TO_CLOB()` aren't really needed, I will get rid of them.

2022-12-30 15:51 UTC, laurenz commented
Thanks! I'll take a close look at that when I come back from vacation on Jan 9.

2023-01-12 12:17 UTC, laurenz requested changes
Your patch looks fine.
I am somewhat surprised that data modifications work without any further ado.

Since you would like me to pull your change request, would you accommodate me in these things:

- please provide a single commit with all your changes, rebased to current git HEAD

- please update the documentation: remove the note that NCLOB is not supported and add a line to the conversion table

If you feel like it, you can also create a CHANGELOG entry. Otherwise, I will add that in a separate commit.

2025-02-04 12:56 UTC, merged

2025-02-04 12:57 UTC, laurenz commented
After only two years, I finally got around to merge this.
Thanks!